site_name: Integrify
site_description: Integrify API inteqrasiyalarını rahatlaşdıran sorğular kitabaxanasıdır.
site_url: https://integrify.mmzeynalli.dev

copyright: Copyright © 2023-2025 Miradil Zeynalli

theme:
  name: material
  custom_dir: ../az/overrides
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/lightbulb-auto
      name: Switch to light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Switch to system preference

    icon:
      repo: fontawesome

  logo: assets/logo.svg
  favicon: assets/favicon.ico
  language: az

repo_name: Integrify-SDK/integrify-docs-python
repo_url: https://github.com/Integrify-SDK/integrify-docs-python

plugins:
  - search
  - panzoom:
      full_screen: True
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [../../src]
          options:
            show_root_heading: true
            show_source: false
            show_if_no_docstring: true
            inherited_members: true
            members_order: source
            # separate_signature: true
            unwrap_annotated: true
            filters:
            - '!^_'
            merge_init_into_class: true
            docstring_section_style: spacy
            signature_crossrefs: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            extensions:
            - griffe_pydantic
  - generate_nav:
      navs_dir: docs/navs
  - multilang
  - translation_placeholder

nav:
  - index.md
  - Resurslar:
    - "resources/index.md"
    - Contibuting: "resources/contributing.md"
    - "resources/code-architecture.md"


markdown_extensions:
  - codehilite:
      guess_lang: false
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.superfences
  - abbr
  - attr_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.highlight:
      line_spans: __span
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tilde

extra:
  alternate:
    - name: Azərbaycanca
      link: /
      lang: az
    - name: English
      link: /en/
      lang: en
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Integrify-SDK/integrify-docs-python
    - icon: fontawesome/solid/globe
      link: https://mmzeynalli.dev
  analytics:
    provider: goatcounter

extra_css:
  - css/termynal.css
  - css/custom.css

extra_javascript:
  - js/custom.js
  - js/termynal.js
